Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?, js
Also need to install plugin dependencies  ["babel-preset-expo"]
add [plugins: ['react-native-reanimated/plugin']] code into babel.config.js